name: Build and Tag Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JFROG_CLI_LOG_LEVEL: DEBUG
        with:
          oidc-provider-name: edenb-374929 
          oidc-audience: jf

      - name: Build Tag and push Docker Image
        env:
          IMAGE_NAME: elinaf.jfrog.io/edenb-docker-ci-docker/docker-example-image:${{ github.run_number }}
        run: |
          jf docker build -t $IMAGE_NAME .
          jf docker push $IMAGE_NAME

      - name: Scan Docker Image for Vulnerabilities
        env:
          IMAGE_NAME: elinaf.jfrog.io/edenb-docker-ci-docker/docker-example-image:${{ github.run_number }}
        run: |
          jf docker scan $IMAGE_NAME

      - name: Publish Build info With JFrog CLI
        env:
          JFROG_CLI_BUILD_NAME: jfrog-docker-build-example
          JFROG_CLI_BUILD_NUMBER : ${{ github.run_number }}
        run: |
          jf rt bce $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
          jf rt bag $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
          jf rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
